import { defineSchema, defineTable } from "convex/server"
import { v } from "convex/values"

export default defineSchema({
  pharmacies: defineTable({
    name: v.string(),
    clerkOrgId: v.string(),
    pharmacyNumber: v.optional(v.string()),
    pharmacySequence: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_clerkOrgId", ["clerkOrgId"])
    .index("by_pharmacySequence", ["pharmacySequence"]),
  users: defineTable({
    clerkUserId: v.string(),
    name: v.optional(v.string()),
    email: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_clerkUserId", ["clerkUserId"]),
  products: defineTable({
    pharmacyId: v.id("pharmacies"),
    name: v.string(),
    barcode: v.string(),
    category: v.string(),
    purchasePrice: v.number(),
    sellingPrice: v.number(),
    vatRate: v.number(),
    stockQuantity: v.number(),
    lowStockThreshold: v.number(),
    dosageForm: v.string(),
    internalNotes: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_pharmacyId", ["pharmacyId"]),
  sales: defineTable({
    pharmacyId: v.id("pharmacies"),
    clientId: v.optional(v.id("clients")),
    sellerId: v.id("users"),
    saleDate: v.number(),
    saleNumber: v.optional(v.string()),
    saleSequence: v.optional(v.number()),
    paymentMethod: v.union(
      v.literal("CASH"),
      v.literal("CARD"),
      v.literal("CHECK"),
      v.literal("CREDIT")
    ),
    globalDiscountType: v.optional(v.union(v.literal("PERCENT"), v.literal("AMOUNT"))),
    globalDiscountValue: v.optional(v.number()),
    totalAmountHt: v.number(),
    totalAmountTtc: v.number(),
    deliveryNoteText: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_pharmacyId", ["pharmacyId"]),
  saleItems: defineTable({
    pharmacyId: v.optional(v.id("pharmacies")),
    saleId: v.id("sales"),
    productId: v.id("products"),
    productNameSnapshot: v.string(),
    quantity: v.number(),
    unitPriceHt: v.number(),
    vatRate: v.number(),
    lineDiscountType: v.optional(v.union(v.literal("PERCENT"), v.literal("AMOUNT"))),
    lineDiscountValue: v.optional(v.number()),
    totalLineTtc: v.number(),
  })
    .index("by_saleId", ["saleId"])
    .index("by_pharmacyId", ["pharmacyId"]),
  suppliers: defineTable({
    pharmacyId: v.id("pharmacies"),
    supplierNumber: v.optional(v.string()),
    supplierSequence: v.optional(v.number()),
    name: v.string(),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    city: v.optional(v.string()),
    balance: v.number(),
    internalNotes: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_pharmacyId", ["pharmacyId"]),
  clients: defineTable({
    pharmacyId: v.id("pharmacies"),
    clientNumber: v.optional(v.string()),
    clientSequence: v.optional(v.number()),
    name: v.string(),
    phone: v.optional(v.string()),
    city: v.optional(v.string()),
    creditLimit: v.number(),
    outstandingBalance: v.number(),
    accountStatus: v.union(v.literal("OK"), v.literal("SURVEILLE"), v.literal("BLOQUE")),
    lastPurchaseDate: v.optional(v.number()),
    internalNotes: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_pharmacyId", ["pharmacyId"]),
  procurementOrders: defineTable({
    pharmacyId: v.id("pharmacies"),
    orderNumber: v.optional(v.string()),
    orderSequence: v.optional(v.number()),
    type: v.union(v.literal("PURCHASE_ORDER"), v.literal("DELIVERY_NOTE")),
    supplierId: v.id("suppliers"),
    status: v.union(v.literal("DRAFT"), v.literal("ORDERED"), v.literal("DELIVERED")),
    externalReference: v.optional(v.string()),
    channel: v.optional(v.union(v.literal("EMAIL"), v.literal("PHONE"))),
    orderDate: v.number(),
    dueDate: v.optional(v.number()),
    globalDiscountType: v.optional(v.union(v.literal("PERCENT"), v.literal("AMOUNT"))),
    globalDiscountValue: v.optional(v.number()),
    totalAmount: v.number(),
    createdAt: v.number(),
  })
    .index("by_pharmacyId", ["pharmacyId"])
    .index("by_pharmacyId_type", ["pharmacyId", "type"]),
  procurementItems: defineTable({
    pharmacyId: v.optional(v.id("pharmacies")),
    orderId: v.id("procurementOrders"),
    productId: v.id("products"),
    quantity: v.number(),
    unitPrice: v.number(),
    lineDiscountType: v.optional(v.union(v.literal("PERCENT"), v.literal("AMOUNT"))),
    lineDiscountValue: v.optional(v.number()),
    lineTotal: v.number(),
  })
    .index("by_orderId", ["orderId"])
    .index("by_pharmacyId", ["pharmacyId"]),
  cashReconciliations: defineTable({
    pharmacyId: v.id("pharmacies"),
    cashNumber: v.optional(v.string()),
    cashSequence: v.optional(v.number()),
    date: v.string(),
    opening: v.number(),
    openingLocked: v.boolean(),
    sales: v.number(),
    withdrawals: v.number(),
    adjustments: v.number(),
    actual: v.number(),
    isLocked: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_pharmacyId", ["pharmacyId"])
    .index("by_pharmacyId_date", ["pharmacyId", "date"]),
})
