import type { Metadata } from "next"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"

import { QaBanner } from "@/components/layout/qa-banner"
import { ThemeProvider } from "@/components/layout/theme-provider"
import { ConvexProvider } from "@/components/providers/convex-provider"
import { Toaster } from "@/components/ui/sonner"
import { getServerEnv } from "@/lib/env/server"

import "./globals.css"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Seraphine",
  description: "Generated by create next app",
}

const env = getServerEnv()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignInUrl="/app"
      afterSignUpUrl="/app"
    >
      <html lang="en" className={inter.variable} suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ConvexProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <QaBanner environment={env.NEXT_PUBLIC_APP_ENV} />
              {children}
              <Toaster />
            </ThemeProvider>
          </ConvexProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
