name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Lint, unit, and E2E tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Lint
        run: pnpm lint

      - name: Unit and integration tests
        run: pnpm test

      - name: Playwright smoke tests
        run: pnpm test:e2e -- --reporter=list
